# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: Act Now

consumes:
  - application/json

produces:
  - application/json

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /demonstration:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Demonstration` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
        -
          name: location
          in: query
          description: location of demonstrations
          required: false
          type: string
      # Expected responses for this operation:
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Demonstration"

    post:
      description: Creates `Demonstration` object
      parameters:
        - name: name
          in: body
          description: Demonstration properties
          required: true
          schema:
            $ref: "#/definitions/Demonstration"

      responses:
        "200":
          description: Succesful response
  /user:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `User` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      # Expected responses for this operation:
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
    post:
      description: add user
      parameters:
        - name: name
          in: body
          description: user properties
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success

  /demonstration/{id}:
    get:
      description: get a demonstration
      parameters:
        -
          name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetDemonstrationResponse"


  /location:
    get:
      description: get location list
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetLocationsResponse"


definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        description: user id
      firstname:
        type: string
        description: user's first name
      lastname:
        type: string
        description: user's last name
      phone:
        type: string
        description: user's phone number
      location:
        type: integer
        description: location id
    required:
      - firstname
      - lastname
      - phone
      - location

  Demonstration:
    type: object
    properties:
      id:
        type: integer
        description: demonstration id
      name:
        type: string
        description: demonstration name
      location:
        type: integer
        description: location id
      causes:
        type: array
        description: array of cause IDs
        items:
          type: integer
          description: cause ID
      description:
        type: string
        description: description of demonstration
      organizer:
        type: integer
        description: organizer's user ID
    required:
      - name
      - location
      - causes
      - description
      - organizer
      
  Location:
    type: object
    properties:
      id:
        type: integer
        description: location id
      name:
        type: string
        description: location name
    required:
        - name
    
  GetDemonstrationResponse:
    description: list of demonstrations
    type: array
    items:
      $ref: "#/definitions/Demonstration"

  GetLocationsResponse:
    description: list of locations
    type: array
    items:
      $ref: "#/definitions/Location"

  ErrorResponse:
    description: error
